### ISSUE TITLE
BUG Paner opens two split windows

### ISSUE THREAD

**Issue by liam-ngy** [t9md/atom-paner#4]
Hey, when I use Paner and want to use split mode, it opens one window more than usual.

![screen shot 2016-08-10 at 11 08 40](https://cloud.githubusercontent.com/assets/8395044/17548726/73256118-5eed-11e6-8417-535ab084ccc3.jpg)

**Comment by t9md** [comment]
Could you explain detail?
What is the operation you did?
What the result?
What the expected result?

**Comment by liam-ngy** [comment]
I can close that issue, fixed with new update

**Comment by t9md** [comment]
Oh, thals for updating result. Good to hear.
